/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaCalc;

/**
 *
 * @author PedroFiveM
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
        panResu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNum = new javax.swing.JSpinner();
        panForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblAreaC = new javax.swing.JLabel();
        lblRaioC = new javax.swing.JLabel();
        lblRaiz = new javax.swing.JLabel();
        lblPote = new javax.swing.JLabel();
        lblAreaCu = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblAreaQ = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();
        panResu = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblReArC = new javax.swing.JLabel();
        lblReC = new javax.swing.JLabel();
        lblReRaiz = new javax.swing.JLabel();
        lblRePote = new javax.swing.JLabel();
        lblReArCu = new javax.swing.JLabel();
        lblReArQ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNum.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        txtNum.setModel(new javax.swing.SpinnerNumberModel());
        txtNum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtNumStateChanged(evt);
            }
        });

        jLabel1.setText("ÁREA CIRCUNFERÊNCIA");

        jLabel2.setText("CIRCUNFERÊNCIA");

        jLabel3.setText("RAIZ");

        jLabel4.setText("POTENCIAÇÃO");

        jLabel5.setText("ÁREA CUBO");

        jLabel6.setText("ÁREA QUADRADO");

        jLabel7.setText("A = π *");

        jLabel8.setText("C =2π");

        jLabel9.setText("√ =");

        jLabel10.setText("^ = ");

        jLabel12.setText("A = 6 *");

        jLabel13.setText("A = ");

        lblAreaC.setText("R");

        lblRaioC.setText("R");

        lblRaiz.setText("RAÍZ");

        lblPote.setText("POTENCIAÇÃO");

        lblAreaCu.setText("A");

        jLabel18.setText("²");

        lblAreaQ.setText("L");

        jLabel20.setText("²");

        javax.swing.GroupLayout panFormLayout = new javax.swing.GroupLayout(panForm);
        panForm.setLayout(panFormLayout);
        panFormLayout.setHorizontalGroup(
            panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(75, 75, 75)
                .addGroup(panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFormLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addComponent(lblAreaC))
                    .addGroup(panFormLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(1, 1, 1)
                        .addComponent(lblRaiz))
                    .addGroup(panFormLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(1, 1, 1)
                        .addComponent(lblPote))
                    .addGroup(panFormLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(1, 1, 1)
                        .addComponent(lblAreaQ)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel20))
                    .addGroup(panFormLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(1, 1, 1)
                        .addComponent(lblAreaCu)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel18))
                    .addGroup(panFormLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(1, 1, 1)
                        .addComponent(lblRaioC))))
        );
        panFormLayout.setVerticalGroup(
            panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(lblAreaC))
                .addGap(18, 18, 18)
                .addGroup(panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRaioC)))
                .addGap(18, 18, 18)
                .addGroup(panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(lblRaiz))
                .addGap(18, 18, 18)
                .addGroup(panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(lblPote))
                .addGap(18, 18, 18)
                .addGroup(panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(lblAreaCu)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(lblAreaQ)
                    .addComponent(jLabel20)))
        );

        btnCalc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalc.setText("CALCULAR");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        jLabel11.setText("RESULTADO ÁREA CIRCUFERÊNCIA = ");

        jLabel14.setText("RESULTADO CIRCUFERÊNCIA =");

        jLabel15.setText("RESULTADO RAIZ =");

        jLabel16.setText("RESULTADO ÁREA CUBO =");

        jLabel17.setText("RESULTADO POTENCIAÇÃO =");

        jLabel19.setText("RESULTADO ÁREA QUADRADO =");

        lblReArC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReArC.setText("0");

        lblReC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReC.setText("0");

        lblReRaiz.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReRaiz.setText("0");

        lblRePote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRePote.setText("0");

        lblReArCu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReArCu.setText("0");

        lblReArQ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReArQ.setText("0");

        javax.swing.GroupLayout panResuLayout = new javax.swing.GroupLayout(panResu);
        panResu.setLayout(panResuLayout);
        panResuLayout.setHorizontalGroup(
            panResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panResuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panResuLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(lblReArQ))
                    .addGroup(panResuLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(lblRePote))
                    .addGroup(panResuLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblReArCu))
                    .addGroup(panResuLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(lblReRaiz))
                    .addGroup(panResuLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblReC))
                    .addGroup(panResuLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReArC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panResuLayout.setVerticalGroup(
            panResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panResuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblReArC))
                .addGap(18, 18, 18)
                .addGroup(panResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblReC))
                .addGap(18, 18, 18)
                .addGroup(panResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblReRaiz))
                .addGap(18, 18, 18)
                .addGroup(panResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblRePote))
                .addGap(18, 18, 18)
                .addGroup(panResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblReArCu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblReArQ))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(panResu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalc))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panResu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtNumStateChanged
        // TODO add your handling code here:
        lblAreaC.setText(txtNum.getValue().toString());
        lblAreaCu.setText(txtNum.getValue().toString());
        lblAreaQ.setText(txtNum.getValue().toString());
        lblPote.setText(txtNum.getValue().toString());
        lblRaioC.setText(txtNum.getValue().toString());
        lblRaiz.setText(txtNum.getValue().toString());
    }//GEN-LAST:event_txtNumStateChanged

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(txtNum.getValue().toString());
        double areaQ, areaC, areaCu, pote, circu, raiz;
        
        //POTENCIAÇÃO
        pote = Math.pow(num, 2);
        lblRePote.setText(String.format("%.2f", pote));
        //ÁREA CIRCUFERÊNCIA
        areaC = 3.14 * num;
        lblReArC.setText(String.format("%.2f", areaC));
        //CIURCUFERÊNCIA
        circu = 2 * 3.14 * num;
        lblReC.setText(String.format("%.2f", circu));
        //RAIZ
        raiz = Math.sqrt(num);
        lblReRaiz.setText(String.format("%.2f", raiz));
        //ÁREA CUBO
        areaCu = 6 * Math.pow(num, 2);
        lblReArCu.setText(String.format("%.2f", areaCu));
        //ÁREA QUADRADO
        areaQ = Math.pow(num, 2);
        lblReArQ.setText(String.format("%.2f", areaQ));
        
        panResu.setVisible(true);
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAreaC;
    private javax.swing.JLabel lblAreaCu;
    private javax.swing.JLabel lblAreaQ;
    private javax.swing.JLabel lblPote;
    private javax.swing.JLabel lblRaioC;
    private javax.swing.JLabel lblRaiz;
    private javax.swing.JLabel lblReArC;
    private javax.swing.JLabel lblReArCu;
    private javax.swing.JLabel lblReArQ;
    private javax.swing.JLabel lblReC;
    private javax.swing.JLabel lblRePote;
    private javax.swing.JLabel lblReRaiz;
    private javax.swing.JPanel panForm;
    private javax.swing.JPanel panResu;
    private javax.swing.JSpinner txtNum;
    // End of variables declaration//GEN-END:variables
}
